### ISSUE TITLE
Animate the concentric circles so that they gently pulsate and fade off like sonar

### ISSUE THREAD

**Issue by benefacto** [dOrgTech/landing-page-v2#111]
Request from @orishim 

<img width="450" alt="Screen_Shot_2021-02-02_at_10 26 11_AM" src="https://user-images.githubusercontent.com/10215679/106645423-2e5c1b80-6541-11eb-9e9c-311b190dc1b8.png">

Might involve some exploration, something along the lines of [this](https://css-tricks.com/animating-svg-css/)

**Comment by orishim** [comment]
Looks amazing! Could this be done with all of the places where the concentric circles appear? (about, careers, contact)
