### ISSUE TITLE
Integrate careers content from Hubspot

### ISSUE THREAD

**Issue by benefacto** [dOrgTech/landing-page-v2#118]
Work with the CRM team to obtain careers content from Hubspot and populate website details on [the careers page](https://polished-fog-7734.on.fleek.co/#/careers).

- [x] Builders
- [x] Quotes
- [x] Positions

**Comment by orishim** [comment]
Probably easiest populate quotes manually.

@steffclearteam @rihp how close are we to having a persona in hubspot for active builders that they can pull the Name, Github, LinkedIn, Portfolio, and Skills data from?

**Comment by steffclearteam** [comment]
We have the infrastructure ( persona and properties ) set up in HubSpot, but I think we are still working on data collection. We need complete builder contact information in a spreadsheet and then we can import that into HubSpot. 

@rihp @orishim I think we started a sheet with builder info called "pre-crm"? Where is that? We can work on filling it up.

**Comment by steffclearteam** [comment]
@orishim we don't have a skills data category - altho we could add that.

**Comment by krisbitney** [comment]
Can we use the "specializations" category as skills for now? I'm looking at: https://airtable.com/tblZc3HquQ9JWZ5BI/viwJrsSAXtRxWrZLN?blocks=hide

**Comment by orishim** [comment]
We want to move entirely away from airtable so I don't think it would make sense to hook up to that API. @steffclearteam just added the "skills" property to the hubspot today. we can give you info on how to access in discord
