### ISSUE TITLE
Misc requests

### ISSUE THREAD

**Issue by krisbitney** [dOrgTech/landing-page-v2#121]
* When a project becomes "sticky", it'd be great to make it not sticky when you click off of it, instead of forcing the user to click it again.
* The front-page footer is duplicated in the pop-over, leading to the viewer being able to see the bottom-most footer, and pop-over footer at the same time
* The scrollbar for the companies is a really great touch! It's a bit hard to see what it is though because it's so dark. Maybe using a light green color to match the radial circle in the bottom right?
* The horizontal bars on the right are amazing to click on! They're a bit small and hard to click on though. Maybe we can make the "hit box" or clickable area bigger without making the visual bar itself bigger so it's easier to click them
* animate all concentric ring graphics to have sonar effects

**Comment by orishim** [comment]
I've spec-ed out the last bullet point in #123
