### ISSUE TITLE
Design Changes: Careers page

### ISSUE THREAD

**Issue by orishim** [dOrgTech/landing-page-v2#123]
## Part 1

Replace 4 panels at the top with a 2 panel diagram (TODO: get this designed by someone)
- Panel 1: high level overview of the dOrg story
- Panel 2: diagram of the builder lifecycle 

Rough wireframe:
<img width="1509" alt="Screen Shot 2021-02-21 at 11 45 06 AM" src="https://user-images.githubusercontent.com/10736693/108631906-4c2ee900-743a-11eb-9606-d1f37c826e3f.png">

## Part 2

Add "Perks" section above "Current Openings" with 5 items:
- 🏖 **100% Remote** - Work from anywhere, anytime with a global team
- ☔️ **Token Airdrops** - Receive org-wide airdrops in proportion to your share of reputation
- 💸 **Commissions** - Earn commissions by referring your friends or sourcing new projects
- 🚀 **Project Launchpad** - Leverage shared resources to launch your own projects 
- 🎡 **Group Benefits** - Enjoy group benefits like discounted tax prep, apparel and more!

Inspiration ([source](https://www.tastemade.com/careers/)):
<img width="1352" alt="Screen Shot 2021-02-03 at 3 55 10 PM" src="https://user-images.githubusercontent.com/10736693/106814657-baa13800-6640-11eb-88af-8b86d0afd8b3.png">

**Comment by orishim** [comment]
We can also add an FAQ section at the bottom based on the copy that @steffclearteam drafted

**Comment by steffclearteam** [comment]
Meeting with Kris 
About Website —> Hubspot

Contacts —> Lists —> dOrg Active Builders

How to map the properties 
- Name - First name / Last Name

Photo - Property URL to image
- Download images and put permanent URL’s into a spreadsheet
- We can import them to HubSpot Avatar Image

Skills Tags - Skills 

Portfolio - GitHub/Portfolio

Builder quotes testimonial about working at dOrg - Create a form and ask people to submit quotes for the carousel 

**For Job Postings**

 https://angel.co/company/dorg-1

- We may want to edit / enhance these job postings - YES!

Create new role - focused descriptions for the careers page. 
- Do not repeat benefits or other requirements. Focus on the role-specific information. Format - Paragraph plus bullet points.

Careers Page - adding 
- Features
- Benefits 

Change CTA on Careers page open Builder Interest Form - 
	https://app.hubspot.com/forms/9179421/editor/a9d37910-18bf-4895-bb53-57397098a053/edit/options

Stylize the email they receive after submitting the form
	https://app.hubspot.com/email/9179421/details/40979057929/performance

**Clients/Sourcing** 

Meet with Ori and Roberto about Contact form
- Do we want to have this simple form and it just populates Hubspot through and API?
- Or do we want to create a more targeted form in HubSpot and rebuild this page?
- In the short term Kris will connect the existing form to HubSpot
- To- Do - create automations to follow up with these submissions
    - General low-touch follow up
