### ISSUE TITLE
Design Changes: Calls to Action

### ISSUE THREAD

**Issue by benefacto** [dOrgTech/landing-page-v2#149]
Request from @steffclearteam , needs designer to finalize
<img width="886" alt="Screen_Shot_2021-02-18_at_2 11 53_PM" src="https://user-images.githubusercontent.com/10215679/108403932-1be61100-71d4-11eb-9b04-204c2841f2c3.png">

**Comment by orishim** [comment]
## Contact Page
- remove "Get in Touch"
- Move "Not sure where.." header up to where "Get in Touch" currently is
- change text below to "Tell us about your project, your timeline, and how you heard about us."
- add a second header in the center that says "Join our community!" with the four icons below that side-by-side: <discord> <twitter> <github> <email>

## Footer
replace the 4 social icons with a button that says "Join our Discord <discord icon>"
