### ISSUE TITLE
Careers: reduce spacing underneath header

### ISSUE THREAD

**Issue by orishim** [dOrgTech/landing-page-v2#181]
Could we make the space under "Discover a new way to.." the same as the space above it? Ideally this would make it so that the entire "Get started by completing an activation challenge." box is visible when scrolled all the way at the top in full screen.

<img width="1527" alt="Screen Shot 2021-02-25 at 1 20 43 AM" src="https://user-images.githubusercontent.com/10736693/109111892-b7f9a600-7707-11eb-8e99-a4d1c42a44dd.png">

**Comment by krisbitney** [comment]
This isn't enough to fit the whole activation challenge box in view. What do you think of also shrinking the other boxes?

Here is a before and after (1080p 16:9 screen):

![Screenshot from 2021-02-25 15-11-44](https://user-images.githubusercontent.com/39842820/109217934-19f3f300-777c-11eb-8883-9107d0dad8b9.png)
![Screenshot from 2021-02-25 15-13-03](https://user-images.githubusercontent.com/39842820/109217935-1a8c8980-777c-11eb-8c93-5cc6b64e3ec8.png)
