### ISSUE TITLE
Add marketing email opt-in checkbox to builder interest form

### ISSUE THREAD

**Issue by krisbitney** [dOrgTech/landing-page-v2#212]
Ernesto: "hi! not sure if this would be the right channel for this request, but would it be possible to add a checkbox on the builder interest form at some point? we'd like to apply this best practice in order to be able to comply with hubspot's email guidelines (among other things); and make sure people opt in to receive emails from dOrg about other things - I can work on the specific wording. we could also potentially add it here [https://dorg.tech/#/contact](https://dorg.tech/#/contact) if possible."

![image](https://user-images.githubusercontent.com/39842820/116587928-8efcb980-a8e0-11eb-8edf-9be4739d4c72.png)

**Comment by orishim** [comment]
closing since we removed the contact form from the website
