### ISSUE TITLE
Add "Blog" page to website with Substack

### ISSUE THREAD

**Issue by orishim** [dOrgTech/landing-page-v2#254]
Add a "Blog" button on the top bar in between Careers and Contact.

Find a way to have our substack blog embedded there. This should help:
https://support.substack.com/hc/en-us/articles/360051222571-How-do-I-set-up-my-custom-domain-

Contact Anna-Marie about access to our substack: https://dorg.substack.com/

**Comment by iralic** [comment]
https://rsilt.substack.com/p/how-i-got-my-substack-to-be-google/comments
Here is a link on how to get substack indexed by Google after implementation.

**Comment by krisbitney** [comment]
> https://rsilt.substack.com/p/how-i-got-my-substack-to-be-google/comments

According to the post, the method no longer works as of September 23, 2021

**Comment by krisbitney** [comment]
@orishim I don't think we can embed the page. We can do an external link. Check out PR#260 and let me know how it looks.

**Comment by iralic** [comment]
Is it possible to have a blog on dorg.tech and be able to publish articles to Substack?  For the purposes of search engine optimization, it would be very helpful to have the original content hosted on the dOrg.tech website.

**Comment by orishim** [comment]
https://support.substack.com/hc/en-us/articles/4407702258836-How-can-I-optimize-my-Substack-publication-for-SEO-

Maybe @elugoruiz knows something about how to optimize further.

**Comment by krisbitney** [comment]
> Is it possible to have a blog on dorg.tech and be able to publish articles to Substack? For the purposes of search engine optimization, it would be very helpful to have the original content hosted on the dOrg.tech website.

I think we would have to maintain two blogs to do that. Substack doesn't have a public API to facilitate automation here.

**Comment by iralic** [comment]
I was going through this today and I didn't know if we had enabled the Google analytics for our substack?  There are a few things we can do to help our content drive traffic based on this article https://rsilt.substack.com/p/how-i-got-my-substack-to-be-google/comments
