### ISSUE TITLE
Attach dorg.tech to Google Search Console

### ISSUE THREAD

**Issue by iralic** [dOrgTech/landing-page-v2#255]
I would like to get Google Search Console up and running.  I signed up using my ira@dorg.tech email address.  In order to verify ownership, I will need this string added to our DNS record.  Can someone who controls the domain please add this text record to our DNS?

google-site-verification=lChjdC6be1zEvWdQKzeGu4l1ypRijH7IlLVwLBvlZI0

**Comment by krisbitney** [comment]
This has been completed.
