### ISSUE TITLE
update footer

### ISSUE THREAD

**Issue by orishim** [dOrgTech/landing-page-v2#269]
@cedricwaxwing what do you think of having the footer show discord, twitter, github, email on the left and just the handbook on the right like this:

<img width="1792" alt="Screen Shot 2022-02-08 at 12 35 06 AM" src="https://user-images.githubusercontent.com/10736693/152932340-16511600-a42f-48ca-a5f8-c985f774c77f.png">

**Comment by orishim** [comment]
(currently you can find these icons in the Contact page, but we are planning on removing that through #264 )

**Comment by cedricwaxwing** [comment]
@orishim Love it. Though, we should still include our copyright text I think?

**Comment by orishim** [comment]
I think it could be excluded
