### ISSUE TITLE
Crop svg used for desktop contact form submission button

### ISSUE THREAD

**Issue by krisbitney** [dOrgTech/landing-page-v2#73]
The svg image used for the submission button in the desktop contact form has a transparent background, and the visible part of the image is not centered. We need to crop the image so that the visible part we care about is centered and so there is minimal background. The positioning of the button may need to be adjusted when the new image is added because a relative positioning modifier was used to mitigate the effect of the off-center shape.

**Comment by krisbitney** [comment]
I can turn the svg into a png and crop it, but i'd like to keep it an svg. Cropping an svg is surprisingly complicated and it would be great to get some advice on the best way to do it.

**Comment by benefacto** [comment]
This should be doable using [Inkscape](https://inkscape.org/)

**Comment by krisbitney** [comment]
> This should be doable using [Inkscape](https://inkscape.org/)

Thanks
